Repository pointnetwork/point-chain, pull requests merged in 2022-09, with the labels that each got.

#47 Mainnet
  Dockerfile
  diagnostic.sh
  faq.md
  init_point_mainnet_local.sh
  scripts/jsts/inflation_schedule_mainnet.ts
  scripts/jsts/inflation_schedule_mainnet.txt
Labels: Type: Build

#51 Add codecov token to fix test pipeline
  .github/workflows/test.yml
Labels: Type: CI

#53 Fix gosec pipeline (#49)
  .github/workflows/security.yml
Labels: Type: CI

#54 Add codecov token
  .github/workflows/test.yml
Labels: Type: CI

#61 Evmos/release/v8.x.x
  .goreleaser.yml
  CHANGELOG.md
  app/app.go
  app/forks.go
  app/upgrades/v8_1/constants.go
  app/upgrades/v8_1/upgrades.go
  app/upgrades/v8_2/constants.go
  docs/validators/overview.md
  docs/validators/upgrades/automated.md
  go.mod
  go.sum
  x/feesplit/module.go
  x/feesplit/types/codec.go
  x/feesplit/types/msg.go
Labels: Type: Docs

#62 Chain id fix tests
  app/upgrades/v4/upgrades_test.go
  types/utils_test.go
Labels: C:Types
